import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { useSession } from "next-auth/react";
import LogInOutButton from '../components/login-btn'

import { useRouter } from 'next/router'

// RedirectPage.getInitialProps = ctx => {
//   // We check for ctx.res to make sure we're on the server.
//   if (ctx.res) {
//     ctx.res.writeHead(302, { Location: '/' });
//     ctx.res.end();
//   }
//   return { };
// }

export default function LoginWrapper(){
    
    const { data: session } = useSession()
    if(session){
        console.log('in LOOOGHIN: ', session);
    
    } else {}

    return(
   
        
        <div className={styles.container}>
        <Head>
          <title>LOGIN!</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
            <h1 className={styles.title}>   
                    {/* <LoginMessage /> */}
                    {session
                    ?
                    // <span>Hi {session.user.name}! Click hub or personal</span>
                    null
                    :
                    <span>You will need to log in!</span>
                    }
                    <LogInOutButton />
            </h1>
        </main>
        <footer className={styles.footer}>
            <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            >
                Powered by{' '}
                <span className={styles.logo}>
                    <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                </span>
            </a>
        </footer>
    </div>
    
    )
}

// function LoginMessage(){
//     const { data: session } = useSession()
//     if(session){
//         console.log('in LOOOGHIN: ', session);
//     } 
//     if(session){
//         return <h2>Yo !</h2>
//     } else {
//         return <h2>You will need to log in</h2>
//     }
// }