import Head from 'next/head';
import Image from 'next/image';
import RegisterNewUser from '../components/registerNewUser';
import styles from '../styles/Home.module.css'
import {useRef} from 'react';
import { useSession } from "next-auth/react";
import LogInOutButton from '../components/login-btn';



export default function LoginWrapper(props){
    
    const allUsers = useRef({});
    

    const { data: session } = useSession();
    // console.log("session ", session);
    // if(session){
    //     console.log('we have a session in /login: ', session);
    // } else {
    //     console.log('no session yet it login');
    // }

  
    if(props && props.allUsers){
        allUsers.current = props.allUsers
    }
  

   
    //console.log("props in login wrapper: ", props);

    return(        
        <div className={styles.container}>

        <Head>
          <title>Login</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main >
            <h1 className={styles.title}>   
                    {session
                    ?
                        <span>Welcome back, {session.user.name}!</span>
                    :
                        <span style={{fontSize:"24px",fontWeight:"100"}}>Create New User</span>
                    }
                    <LogInOutButton allUsers={allUsers.current} />
                    {/* <RegisterNewUser /> */}
            </h1>
        </main>
    </div>
    )
}

