import Head from 'next/head';
import Image from 'next/image';
import RegisterNewUser from '../components/registerNewUser';
import styles from '../styles/Home.module.css'
import {createRef, useContext} from 'react';
import { useSession } from "next-auth/react";
import LogInOutButton from '../components/login-btn';



export default function LoginWrapper(){
    
    const { data: session } = useSession()
    if(session){
        console.log('in /login: ', session);
    } else {}
    let src = "https://thumbs.gfycat.com/EntireSneakyDog-size_restricted.gif"
    return(
   
        
        <div className={styles.container}>
                        <Image 
                            style={{zIndex:"-1",color:"rgba(0, 112, 243, 0.5)",backgroundColor:"rgba(0, 112, 243, 0.5)",background:"rgba(0, 112, 243, 0.5)"}}
                            unoptimized
                            alt="FarmScene"
                            // width={500}
                            // height={500}
                            loader={() => src}
                            layout="fill"
                            src={src}
                        />
        <Head>
          <title>LOGIN!</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main >
            <h1 className={styles.title}>   
                    {/* <LoginMessage /> */}
                    {session
                    ?
                    <span>Hi {session.user.email}! Click hub or personal</span>
                    // null
                    :
                    <span style={{fontSize:"32px"}}>You will need to log in!</span>
                    }
                    <LogInOutButton />
                    {/* <RegisterNewUser /> */}
            </h1>
        </main>
    </div>
    
    )
}

